export const productCategories = [
  'Proteínas',
  'Creatina & Fuerza',
  'Pre-entreno & Energía',
  'Recuperación & Aminoácidos',
  'Vitaminas & Minerales',
  'Salud & Bienestar',
  'Control de peso',
  'For Her',
] as const

export type ProductCategory = (typeof productCategories)[number]

export type Product = {
  id: string
  tariffRef?: string
  name: string
  price: number
  regularPrice?: number
  image: string
  flavors: string[]
  description: string
  longDescription: string
  category: ProductCategory
  categories: ProductCategory[]
  badge?: string
  format: string
  serving?: string
  use: string
  ingredients?: string
  technical: Array<{ label: string; value: string }>
  officialUrl?: string
  note?: string
}

const officialImage = (name: string) => `/api/product-image?name=${encodeURIComponent(name)}`

export const products: Product[] = [
  {
    id: 'whey-pro-concentrate-2kg',
    tariffRef: 'BEVWPCHC',
    name: 'Whey Pro Concentrate 2kg',
    price: 75,
    image: officialImage('WHEY PRO CONCENTRATE Choco Cookies Lacprodan 2kg'),
    flavors: ['Banana', 'Belgian Choco', 'Butter Biscuit', 'Choco Cookies', 'Natillas', 'Strawberry', 'Strawberry White Choco', 'Vanilla Ice Cream'],
    description: 'Proteína de suero concentrada Lacprodan® con enzimas digestivas.',
    longDescription: 'Whey concentrada en formato 2 kg. La gama 2026 aparece en ocho sabores en la tarifa profesional Beverly.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Producto estrella',
    format: '2 kg en polvo',
    serving: '35 g',
    use: 'Mezclar la ración indicada en el envase con agua, leche o bebida vegetal.',
    technical: [{ label: 'Formato', value: '2 kg' }, { label: 'Base', value: 'Proteína de suero Lacprodan®' }, { label: 'Tarifa 2026', value: 'PVP 75,00 €' }],
    officialUrl: 'https://beverly.es/products/whey-pro-concentrate-2kg-choco-cookies',
  },
  {
    id: 'casein-professional-1kg',
    tariffRef: 'BEVCASC',
    name: 'Casein Professional 1kg',
    price: 45,
    image: officialImage('CASEIN PROFESSIONAL Choco 1kg'),
    flavors: ['Chocolate', 'Strawberry', 'Vanilla'],
    description: 'Caseína profesional en formato 1 kg.',
    longDescription: 'Proteína de digestión sostenida. La tarifa 2026 incluye Chocolate, Strawberry y Vanilla.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '1 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Utilizar según la ración indicada en el envase y el plan nutricional.',
    technical: [{ label: 'Formato', value: '1 kg' }, { label: 'Tipo', value: 'Caseína' }, { label: 'Tarifa 2026', value: 'PVP 45,00 €' }],
  },
  {
    id: 'vegan-protein-900g',
    tariffRef: 'BEVVGCHC',
    name: 'Vegan Delicatesse 900g',
    price: 30,
    image: officialImage('VEGAN DELICATESSE Choco Cookies 900g'),
    flavors: ['Choco Cookies', 'Petit Beurre', 'Strawberry White Choco'],
    description: 'Proteína vegetal en tres sabores de la gama 2026.',
    longDescription: 'Alternativa vegetal de Beverly en formato 900 g.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Salud & Bienestar'],
    format: '900 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con agua o bebida vegetal.',
    technical: [{ label: 'Formato', value: '900 g' }, { label: 'Tipo', value: 'Proteína vegetal' }, { label: 'Tarifa 2026', value: 'PVP 30,00 €' }],
  },
  {
    id: 'creatina-500g',
    tariffRef: 'BEVCR500',
    name: 'Creatina Monohidrato 500g',
    price: 43,
    image: officialImage('CREATINE MONOHIDRATE 500'),
    flavors: ['Sin sabor'],
    description: 'Creatina monohidrato en formato 500 g.',
    longDescription: 'Formato grande y sencillo de creatina monohidrato.',
    category: 'Creatina & Fuerza',
    categories: ['Creatina & Fuerza'],
    badge: '500 g',
    format: '500 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada por el fabricante.',
    ingredients: 'Creatina monohidrato.',
    technical: [{ label: 'Formato', value: '500 g' }, { label: 'Sabor', value: 'Neutro' }, { label: 'Tarifa 2026', value: 'PVP 43,00 €' }],
  },
  {
    id: 'bcaa-811-300g',
    tariffRef: 'BEV811T',
    name: 'BCAA 8:1:1 300g',
    price: 32.82,
    image: officialImage('BCAA 8:1:1 Branched Aminoacids Blue lollipop 300gr'),
    flavors: ['Blue Lollipop'],
    description: 'Aminoácidos ramificados BCAA 8:1:1 en polvo.',
    longDescription: 'Referencia BCAA de la tarifa 2026 en formato 300 g.',
    category: 'Recuperación & Aminoácidos',
    categories: ['Recuperación & Aminoácidos'],
    format: '300 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosificación indicada en el envase.',
    technical: [{ label: 'Ratio', value: '8:1:1' }, { label: 'Formato', value: '300 g' }, { label: 'Tarifa 2026', value: 'PVP 32,82 €' }],
  },
  {
    id: 'map-300g',
    tariffRef: 'BEVMAP',
    name: 'M.A.P. Essential Amino Acids 300g',
    price: 38.5,
    image: officialImage('M.A.P Essential Aminoacids Blue lollipop 300 gr'),
    flavors: ['Blue Lollipop', 'Watermelon'],
    description: 'Fórmula de aminoácidos esenciales en polvo.',
    longDescription: 'M.A.P. aparece en la tarifa 2026 en Blue Lollipop y Watermelon.',
    category: 'Recuperación & Aminoácidos',
    categories: ['Recuperación & Aminoácidos'],
    format: '300 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosificación indicada en el envase.',
    technical: [{ label: 'Tipo', value: 'Aminoácidos esenciales' }, { label: 'Formato', value: '300 g' }, { label: 'Tarifa 2026', value: 'PVP 38,50 €' }],
  },
  {
    id: 'dynamite-pre-workout',
    tariffRef: 'BEVDYFP',
    name: 'Dynamite Pre-Workout 375g',
    price: 33.9,
    image: officialImage('DYNAMITE PREWORKOUT Fruit Punch 375 gr'),
    flavors: ['Fruit Punch', 'Lollipop'],
    description: 'Pre-entreno en polvo de la gama Beverly.',
    longDescription: 'Pre-workout en formato 375 g. Contiene estimulantes; revisar siempre las advertencias del envase.',
    category: 'Pre-entreno & Energía',
    categories: ['Pre-entreno & Energía', 'Creatina & Fuerza'],
    format: '375 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Tomar únicamente según la dosificación y advertencias del fabricante.',
    technical: [{ label: 'Formato', value: '375 g' }, { label: 'Categoría', value: 'Pre-entreno' }, { label: 'Tarifa 2026', value: 'PVP 33,90 €' }],
    note: 'Contiene estimulantes. Revisar contraindicaciones y advertencias completas del envase.',
  },
  {
    id: 'energy-pro-90',
    tariffRef: 'BEVEPRO',
    name: 'Energy Pro 90 caps',
    price: 15.97,
    image: officialImage('ENERGY PRO Caffeine L-Taurine 90 caps'),
    flavors: ['Cápsulas'],
    description: 'Cafeína y L-taurina en cápsulas.',
    longDescription: 'Referencia de energía en formato 90 cápsulas.',
    category: 'Pre-entreno & Energía',
    categories: ['Pre-entreno & Energía'],
    format: '90 cápsulas',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase y evitar combinar con exceso de cafeína.',
    technical: [{ label: 'Formato', value: '90 cápsulas' }, { label: 'Fórmula', value: 'Cafeína + L-Taurina' }, { label: 'Tarifa 2026', value: 'PVP 15,97 €' }],
    note: 'Contiene cafeína.',
  },
  {
    id: 'vitamin-complex-90',
    tariffRef: 'BEVVC',
    name: 'Vitamin Complex 90 caps',
    price: 19.9,
    image: officialImage('VITAMIN COMPLEX 90 caps'),
    flavors: ['Cápsulas'],
    description: 'Complejo diario de vitaminas y minerales.',
    longDescription: 'Multivitamínico y mineral de la línea Beverly.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar'],
    format: '90 cápsulas',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Formato', value: '90 cápsulas' }, { label: 'Tipo', value: 'Multivitamínico y mineral' }, { label: 'Tarifa 2026', value: 'PVP 19,90 €' }],
  },
  {
    id: 'isolate-cfm-1kg',
    tariffRef: 'BEVICFMCHC1',
    name: 'Isolate CFM Professional 1kg',
    price: 52,
    image: officialImage('ISOLATE CFM Choco Cookies 1kg Lacprodan'),
    flavors: ['Butter Biscuit', 'Choco Cookies', 'Choco Hazelnut', 'Strawberry', 'Banana', 'Vanilla'],
    description: 'Aislado de suero CFM Lacprodan® en formato 1 kg.',
    longDescription: 'Proteína aislada de la gama profesional Beverly.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Aislado',
    format: '1 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con agua, leche o bebida vegetal.',
    technical: [{ label: 'Formato', value: '1 kg' }, { label: 'Base', value: 'Isolate CFM Lacprodan®' }, { label: 'Tarifa 2026', value: 'PVP 52,00 €' }],
  },
  {
    id: 'isolate-cfm-2kg',
    tariffRef: 'BEVICFMCHC',
    name: 'Isolate CFM Professional 2kg',
    price: 94.9,
    image: officialImage('ISOLATE CFM Choco Cookies 2kg Lacprodan'),
    flavors: ['Butter Biscuit', 'Choco Cookies', 'Choco Hazelnut', 'Strawberry', 'Strawberry Cheesecake', 'Vanilla'],
    description: 'Aislado CFM Lacprodan® en formato 2 kg.',
    longDescription: 'Formato grande del aislado CFM Professional.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Formato ahorro',
    format: '2 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con agua, leche o bebida vegetal.',
    technical: [{ label: 'Formato', value: '2 kg' }, { label: 'Base', value: 'Isolate CFM Lacprodan®' }, { label: 'Tarifa 2026', value: 'PVP 94,90 €' }],
  },
  {
    id: 'hydro-protein-1kg',
    tariffRef: 'BEVDLCHC',
    name: 'Hydro Protein 1kg',
    price: 47,
    image: officialImage('HYDRO PROTEIN Choco Cookies 1kg'),
    flavors: ['Choco Cookies', 'Petit Beurre', 'Strawberry Cheesecake', 'Strawberry White Chocolate', 'Choco Orange', 'Yogurt Peach', 'Sweet Pineapple', 'Choco Raspberry', 'Choco Hazelnut', 'Lemon Cheesecake', 'Custard Ice Cream', 'Banana'],
    description: 'Proteína hidrolizada en formato 1 kg.',
    longDescription: 'Gama Hydro Protein / Delicatesse Hydrolyzed con amplia variedad de sabores en la tarifa 2026.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '1 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con agua, leche o bebida vegetal.',
    technical: [{ label: 'Tipo', value: 'Proteína hidrolizada' }, { label: 'Formato', value: '1 kg' }, { label: 'Tarifa 2026', value: 'PVP 47,00 €' }],
  },
  {
    id: 'hydro-protein-2kg',
    tariffRef: 'BEVHCH',
    name: 'Hydrolyzed Zero Professional 2kg',
    price: 85,
    image: officialImage('HYDROLYZED ZERO PROFESSIONAL Chocolate 2kg'),
    flavors: ['Chocolate', 'Strawberry', 'Cookies & Cream'],
    description: 'Proteína hidrolizada profesional en formato 2 kg.',
    longDescription: 'Formato 2 kg de la gama Hydrolyzed Zero Professional.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '2 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con agua, leche o bebida vegetal.',
    technical: [{ label: 'Tipo', value: 'Proteína hidrolizada' }, { label: 'Formato', value: '2 kg' }, { label: 'Tarifa 2026', value: 'PVP 85,00 €' }],
  },
  {
    id: 'clear-isolate-500g',
    tariffRef: 'BEVCLCC',
    name: 'Isolate Clear Professional 500g',
    price: 31.9,
    image: officialImage('ISOLATE CLEAR PROFESS Caribbean cooler 500g Lacprodan'),
    flavors: ['Caribbean Cooler', 'Strawberry Kiwi'],
    description: 'Aislado de suero tipo clear en formato 500 g.',
    longDescription: 'Bebida proteica ligera. Orange Mango figura en la tarifa como formato distinto de 908 g y no se mezcla en esta referencia.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Clear',
    format: '500 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar preferiblemente con agua fría según la etiqueta.',
    technical: [{ label: 'Formato', value: '500 g' }, { label: 'Base', value: 'Isolate Clear Lacprodan®' }, { label: 'Tarifa 2026', value: 'PVP 31,90 €' }],
  },
  {
    id: 'pure-whey-1kg',
    tariffRef: 'BEVPURE',
    name: 'Pure Whey 1kg',
    price: 49,
    image: officialImage('PURE WHEY Unflavored Lacprodan 1kg'),
    flavors: ['Unflavored'],
    description: 'Whey Lacprodan® sin sabor añadido.',
    longDescription: 'Referencia de proteína de suero sin sabor en formato 1 kg.',
    category: 'Proteínas',
    categories: ['Proteínas'],
    format: '1 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con la bebida elegida.',
    technical: [{ label: 'Formato', value: '1 kg' }, { label: 'Sabor', value: 'Unflavored' }, { label: 'Tarifa 2026', value: 'PVP 49,00 €' }],
  },
  {
    id: 'whey-pro-concentrate-1kg',
    tariffRef: 'BEVWPCHC1',
    name: 'Whey Pro Concentrate 1kg',
    price: 41.65,
    image: officialImage('WHEY PRO CONCENTRATE Choco Cookies 1kg Lacprodan'),
    flavors: ['Butter Biscuit', 'Choco Cookies', 'Natillas', 'Strawberry Cheesecake', 'Strawberry', 'Vanilla'],
    description: 'Whey Pro Concentrate en formato 1 kg.',
    longDescription: 'Formato compacto del concentrado de suero Lacprodan®.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '1 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con agua, leche o bebida vegetal.',
    technical: [{ label: 'Formato', value: '1 kg' }, { label: 'Base', value: 'Whey Lacprodan®' }, { label: 'Tarifa 2026', value: 'PVP 41,65 €' }],
  },
  {
    id: 'creapure-300g',
    tariffRef: 'BVCRP300',
    name: 'Creatina Monohidrato Creapure® 300g',
    price: 32.95,
    image: officialImage('CREATINE Creapure 300g'),
    flavors: ['Unflavored'],
    description: 'Creatina monohidrato Creapure® en formato 300 g.',
    longDescription: 'La variante Cherry tiene un PVP distinto en la tarifa 2026, por lo que se mantiene separada de esta referencia hasta soportar precios por variante.',
    category: 'Creatina & Fuerza',
    categories: ['Creatina & Fuerza'],
    badge: 'Creapure®',
    format: '300 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Formato', value: '300 g' }, { label: 'Calidad', value: 'Creapure®' }, { label: 'Tarifa 2026', value: 'PVP 32,95 €' }],
  },
  {
    id: 'creapure-q10-300g',
    tariffRef: 'BVCRW',
    name: 'Creatina Creapure® + Q10 300g',
    price: 33.9,
    image: officialImage('CREATINE Creapure Q10 Watermelon 300 gr'),
    flavors: ['Watermelon'],
    description: 'Creatina Creapure® con coenzima Q10.',
    longDescription: 'Referencia de la colección For Her con sabor Watermelon.',
    category: 'Creatina & Fuerza',
    categories: ['Creatina & Fuerza', 'For Her'],
    format: '300 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Formato', value: '300 g' }, { label: 'Fórmula', value: 'Creapure® + Q10' }, { label: 'Tarifa 2026', value: 'PVP 33,90 €' }],
  },
  {
    id: 'nac-90',
    tariffRef: 'BEVNAC',
    name: 'NAC + Vitamina C & Zinc 90 caps',
    price: 15.5,
    image: officialImage('NAC N-Acetil L-Cysteine Vit C Zinc 90 caps'),
    flavors: ['Cápsulas'],
    description: 'N-acetil L-cisteína combinada con vitamina C y zinc.',
    longDescription: 'Sustituye a la L-citrulina que no aparece en la tarifa profesional 2026 facilitada.',
    category: 'Salud & Bienestar',
    categories: ['Salud & Bienestar', 'Vitaminas & Minerales'],
    format: '90 cápsulas',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Fórmula', value: 'NAC + Vitamina C + Zinc' }, { label: 'Formato', value: '90 cápsulas' }, { label: 'Tarifa 2026', value: 'PVP 15,50 €' }],
  },
  {
    id: 'l-glutamina-kyowa-300g',
    tariffRef: 'BEVGMN',
    name: 'L-Glutamina Kyowa® 300g',
    price: 19.2,
    image: officialImage('L-GLUTAMINE Kyowa Neutra 300gr'),
    flavors: ['Neutra'],
    description: 'L-glutamina Kyowa® en polvo.',
    longDescription: 'La variante neutra tiene PVP 19,20 €; Cherry y Lollipop figuran a 19,00 € y se separarán cuando el carrito soporte precio por variante.',
    category: 'Recuperación & Aminoácidos',
    categories: ['Recuperación & Aminoácidos', 'Salud & Bienestar'],
    format: '300 g en polvo',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosificación indicada en el envase.',
    technical: [{ label: 'Ingrediente', value: 'L-Glutamina Kyowa®' }, { label: 'Formato', value: '300 g' }, { label: 'Tarifa 2026', value: 'PVP 19,20 €' }],
  },
  {
    id: 'magnesium-bisglycinate-b6',
    tariffRef: 'BEVMAG',
    name: 'Magnesium Bisglycinate 90 caps',
    price: 12.95,
    image: officialImage('MAGNESIUM BISGLYCINATE 90 caps'),
    flavors: ['Cápsulas'],
    description: 'Magnesio bisglicinato en formato 90 cápsulas.',
    longDescription: 'Referencia de la línea Health 2026.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar'],
    format: '90 cápsulas',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Tipo', value: 'Bisglicinato de magnesio' }, { label: 'Formato', value: '90 cápsulas' }, { label: 'Tarifa 2026', value: 'PVP 12,95 €' }],
  },
  {
    id: 'vitamin-d3-k2',
    tariffRef: 'BEVVITDK',
    name: 'Vitamina D3 + K2 60 caps',
    price: 12.9,
    image: officialImage('VITAMIN D3 K2 60 vegan caps'),
    flavors: ['Cápsulas'],
    description: 'Combinación de vitamina D3 y vitamina K2.',
    longDescription: 'Referencia de vitaminas en formato 60 cápsulas veganas.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar', 'For Her'],
    format: '60 cápsulas veganas',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Fórmula', value: 'Vitamina D3 + K2' }, { label: 'Formato', value: '60 cápsulas' }, { label: 'Tarifa 2026', value: 'PVP 12,90 €' }],
  },
  {
    id: 'ashwagandha-ksm66',
    tariffRef: 'BEVASH',
    name: 'Ashwagandha KSM-66® 60 caps',
    price: 29.5,
    image: officialImage('ASHWAGANDHA KSM-66 Magnesio L-Teanina Rhodiola 60 vegan caps'),
    flavors: ['Cápsulas'],
    description: 'KSM-66® con magnesio, L-teanina y rhodiola.',
    longDescription: 'Fórmula de la línea Health que también aparece en la selección For Her.',
    category: 'Salud & Bienestar',
    categories: ['Salud & Bienestar', 'For Her'],
    format: '60 cápsulas veganas',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Fórmula', value: 'KSM-66® + Magnesio + L-Teanina + Rhodiola' }, { label: 'Formato', value: '60 cápsulas' }, { label: 'Tarifa 2026', value: 'PVP 29,50 €' }],
  },
  {
    id: 'b-complex-60',
    tariffRef: 'BEVBCOM',
    name: 'B-Complex 100 · 60 tabs',
    price: 28,
    image: officialImage('B-COMPLEX 100 60 tabs'),
    flavors: ['Comprimidos'],
    description: 'Complejo de vitaminas del grupo B.',
    longDescription: 'B-Complex 100 de la gama de vitaminas Beverly.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar'],
    format: '60 comprimidos',
    serving: 'Consultar etiqueta',
    use: 'Seguir la dosis indicada en el envase.',
    technical: [{ label: 'Tipo', value: 'Complejo de vitaminas B' }, { label: 'Formato', value: '60 comprimidos' }, { label: 'Tarifa 2026', value: 'PVP 28,00 €' }],
  },
  {
    id: 'women-protein-1kg',
    tariffRef: 'BEVWPSCH',
    name: 'Women Protein Shake 1kg',
    price: 49,
    image: officialImage('WOMEN PROTEIN SHAKE Chocolate 1kg'),
    flavors: ['Capuccino', 'Chocolate', 'Strawberry White Choco', 'Petit Beurre'],
    description: 'Protein shake de la colección For Her en formato real de 1 kg.',
    longDescription: 'La tarifa 2026 confirma formato 1 kg; se corrige la ficha anterior de 500 g.',
    category: 'For Her',
    categories: ['For Her', 'Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'For Her',
    format: '1 kg en polvo',
    serving: 'Consultar etiqueta',
    use: 'Mezclar la ración indicada con agua, leche o bebida vegetal.',
    technical: [{ label: 'Formato', value: '1 kg' }, { label: 'Colección', value: 'For Her' }, { label: 'Tarifa 2026', value: 'PVP 49,00 €' }],
  },
  {
    id: 'collagen-for-her-20',
    tariffRef: 'BEVCOL',
    name: 'Collagen Beauty & Health 20 viales',
    price: 37,
    image: officialImage('COLLAGEN BEAUTY HEALTH Biotina Ácido hialurónico Vit C Zinc 20 viales'),
    flavors: ['20 viales'],
    description: 'Colágeno con biotina, ácido hialurónico, vitamina C y zinc.',
    longDescription: 'Referencia rebranding 2026 de la colección For Her.',
    category: 'For Her',
    categories: ['For Her', 'Salud & Bienestar'],
    format: '20 viales',
    serving: 'Consultar etiqueta',
    use: 'Seguir la pauta indicada en el envase.',
    technical: [{ label: 'Formato', value: '20 viales' }, { label: 'Fórmula', value: 'Colágeno + Biotina + Ácido hialurónico + Vit. C + Zinc' }, { label: 'Tarifa 2026', value: 'PVP 37,00 €' }],
  },
  {
    id: 'burner-extreme-90',
    tariffRef: 'BEVBE',
    name: 'Burner Extreme 90 caps',
    price: 37.15,
    image: officialImage('BURNER EXTREME Sinetrol L-Carnitina Naranja amarga 90 caps'),
    flavors: ['Cápsulas'],
    description: 'Fórmula de control de peso con estimulantes.',
    longDescription: 'Producto de la categoría Fat Burners & Diuretics. No sustituye dieta, entrenamiento ni descanso.',
    category: 'Control de peso',
    categories: ['Control de peso', 'Pre-entreno & Energía'],
    format: '90 cápsulas',
    serving: 'Consultar etiqueta',
    use: 'Seguir estrictamente la dosis y las advertencias del fabricante.',
    technical: [{ label: 'Categoría', value: 'Control de peso' }, { label: 'Formato', value: '90 cápsulas' }, { label: 'Tarifa 2026', value: 'PVP 37,15 €' }],
    note: 'Contiene ingredientes estimulantes. Revisar contraindicaciones y advertencias del envase.',
  },
  {
    id: 'carni-xtreme-20',
    tariffRef: 'BEVCX4000',
    name: 'Carni Xtreme 4000 · 20 shots',
    price: 31,
    image: officialImage('CARNI XTREME 4000 Frutos Rojos 20 Shots'),
    flavors: ['Frutos rojos'],
    description: 'L-carnitina líquida en formato 20 shots.',
    longDescription: 'Referencia líquida de la categoría de control de peso.',
    category: 'Control de peso',
    categories: ['Control de peso', 'Pre-entreno & Energía'],
    format: '20 shots',
    serving: 'Consultar etiqueta',
    use: 'Seguir la pauta indicada en el envase.',
    technical: [{ label: 'Formato', value: '20 shots' }, { label: 'Sabor', value: 'Frutos rojos' }, { label: 'Tarifa 2026', value: 'PVP 31,00 €' }],
  },
  {
    id: 'energy-go-gel-12',
    tariffRef: 'BEVEGA',
    name: 'Energy Go Gel · 12 sticks',
    price: 23.75,
    image: officialImage('ENERGY GO GEL PREWORKOUT Apple 12x73,2g'),
    flavors: ['Apple', 'Orange', 'Cola'],
    description: 'Gel energético en formato individual.',
    longDescription: 'Caja de 12 sticks disponible en tres sabores con el mismo PVP en la tarifa 2026.',
    category: 'Pre-entreno & Energía',
    categories: ['Pre-entreno & Energía'],
    format: '12 sticks',
    serving: '1 stick',
    use: 'Utilizar según las indicaciones del envase y las necesidades de la actividad deportiva.',
    technical: [{ label: 'Formato', value: '12 sticks' }, { label: 'Categoría', value: 'Energía' }, { label: 'Tarifa 2026', value: 'PVP 23,75 €' }],
  },
]

export const collagenPromo: Product = {
  id: 'promo-colageno-2-cajas',
  tariffRef: 'BEVCOL',
  name: 'Pack Collagen Beauty & Health · 2 cajas',
  price: 65,
  regularPrice: 74,
  image: officialImage('COLLAGEN BEAUTY HEALTH Biotina Ácido hialurónico Vit C Zinc 20 viales'),
  flavors: ['40 viales'],
  description: 'Dos cajas de 20 viales de Collagen Beauty & Health.',
  longDescription: 'Pack promocional GHC de dos cajas. El PVP individual de tarifa 2026 es 37,00 € por caja.',
  category: 'For Her',
  categories: ['For Her', 'Salud & Bienestar'],
  badge: 'Pack ahorro',
  format: '2 × 20 viales',
  serving: 'Consultar etiqueta',
  use: 'Seguir la pauta indicada en el envase.',
  technical: [{ label: 'Contenido', value: '40 viales' }, { label: 'PVP conjunto tarifa', value: '74,00 €' }, { label: 'Precio pack GHC', value: '65,00 €' }],
}

export const catalog = [collagenPromo, ...products]

export function getProduct(productId: string) {
  return catalog.find((product) => product.id === productId)
}

export function formatPrice(value: number) {
  return new Intl.NumberFormat('es-ES', {
    style: 'currency',
    currency: 'EUR',
  }).format(value)
}
