export const productCategories = [
  'Proteínas',
  'Creatina & Fuerza',
  'Pre-entreno & Energía',
  'Recuperación & Aminoácidos',
  'Vitaminas & Minerales',
  'Salud & Bienestar',
  'Control de peso',
  'For Her',
] as const

export type ProductCategory = (typeof productCategories)[number]

export type Product = {
  id: string
  name: string
  price: number
  regularPrice?: number
  image: string
  flavors: string[]
  officialFlavors?: string[]
  description: string
  longDescription: string
  category: ProductCategory
  categories: ProductCategory[]
  badge?: string
  format: string
  serving?: string
  use: string
  ingredients?: string
  technical: Array<{ label: string; value: string }>
  officialUrl?: string
  note?: string
}

const officialImage = (name: string) => `/api/product-image?name=${encodeURIComponent(name)}`

export const products: Product[] = [
  {
    id: 'whey-pro-concentrate-2kg',
    name: 'Whey Pro Concentrate 2kg',
    price: 72.9,
    image: officialImage('Whey Pro Concentrate - 2 Kg - Choco Cookies'),
    flavors: ['Choco Cookies', 'Strawberry', 'Vainilla Ice Cream', 'Banana'],
    description: 'Proteína de suero concentrada Lacprodan® con enzimas digestivas.',
    longDescription: 'Whey concentrada para completar el aporte diario de proteína. Beverly formula esta gama con Lacprodan® SP-8011, DigeZyme® y Tolerase® L.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Producto estrella',
    format: '2 kg en polvo',
    serving: '35 g',
    use: 'Mezclar 35 g con agua, leche o bebida vegetal. Revisar la etiqueta física ante cambios de formulación.',
    technical: [{ label: 'Proteína por toma', value: '26,8–27,4 g según sabor' }, { label: 'DigeZyme®', value: '35 mg' }, { label: 'Tolerase® L', value: '17,5 mg' }],
    officialUrl: 'https://beverly.es/products/whey-pro-concentrate-2kg-choco-cookies',
  },
  {
    id: 'micellar-caseina-1kg',
    name: 'Caseína Micelar 1kg',
    price: 32.5,
    image: officialImage('Caseína Micelar - 1 Kg - Butter Biscuit'),
    flavors: ['Butter Biscuit', 'Salted Caramel', 'Choco Cookies'],
    description: 'Caseína micelar de liberación sostenida con DigeZyme® y Tolerase® L.',
    longDescription: 'Proteína de digestión lenta para completar el aporte proteico durante periodos largos entre tomas.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '1 kg en polvo',
    serving: '35 g',
    use: 'Mezclar 35 g con agua, leche o bebida vegetal.',
    technical: [{ label: 'Proteína', value: '27,3 g por 35 g (Butter Biscuit)' }, { label: 'Hidratos', value: '2 g por 35 g' }, { label: 'DigeZyme®', value: '35 mg' }],
    officialUrl: 'https://beverly.es/products/casein-professional-1-kg-butter-biscuit',
  },
  {
    id: 'vegan-protein-900g',
    name: 'Vegan Protein 900g',
    price: 27.9,
    image: officialImage('Vegan Protein - 900 g - Choco Cookies'),
    flavors: ['Choco Cookies', 'Strawberry White Choco', 'Petit Beurre'],
    description: 'Proteína vegetal de guisante y arroz con mezcla botánica.',
    longDescription: 'Combina aislados de proteína vegetal con quinoa, chlorella, chía, espirulina, moringa, psyllium y DigeZyme®.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Salud & Bienestar'],
    format: '900 g en polvo',
    serving: '30 g en tabla nutricional',
    use: 'Mezclar una toma con agua o bebida vegetal. Prevalece la etiqueta física del envase.',
    technical: [{ label: 'Proteína', value: '23 g por 30 g' }, { label: 'DigeZyme®', value: '30 mg' }],
    officialUrl: 'https://beverly.es/products/vegan-protein-900-g-choco-cookies',
  },
  {
    id: 'creatina-500g',
    name: 'Creatina Monohidrato 500g',
    price: 39.9,
    image: officialImage('Creatina Monohidrato - 500 g - Unflavored'),
    flavors: ['Sin sabor'],
    description: 'Creatina monohidrato sin sabor y sin mezclas.',
    longDescription: 'Formato de 500 g de creatina monohidrato para una pauta diaria sencilla.',
    category: 'Creatina & Fuerza',
    categories: ['Creatina & Fuerza'],
    badge: '100% creatina',
    format: '500 g en polvo',
    serving: '3 g',
    use: 'Mezclar 3 g en aproximadamente 200 ml de agua.',
    ingredients: 'Creatina monohidrato.',
    technical: [{ label: 'Creatina monohidrato', value: '3 g por servicio' }, { label: 'Sabor', value: 'Neutro' }],
    officialUrl: 'https://beverly.es/products/creatina-monohidrato-500-g-unflavored',
  },
  {
    id: 'bcaa-811-300g',
    name: 'BCAA 8:1:1 + L-Glutamina 300g',
    price: 26.9,
    image: officialImage('BCAA 8:1:1 + L-Glutamina - 300 g - Blue Lollipop'),
    flavors: ['Blue Lollipop', 'Watermelon'],
    description: 'BCAA en ratio 8:1:1 con L-glutamina y vitamina B6.',
    longDescription: 'Fórmula de aminoácidos ramificados con predominio de leucina, complementada con L-glutamina y vitamina B6.',
    category: 'Recuperación & Aminoácidos',
    categories: ['Recuperación & Aminoácidos'],
    format: '300 g en polvo',
    serving: '10 g',
    use: 'Mezclar 10 g en unos 200 ml de agua. Comprobar el dosificador de la unidad física.',
    technical: [{ label: 'L-Leucina', value: '4.000 mg' }, { label: 'L-Glutamina', value: '1.500 mg' }, { label: 'L-Isoleucina', value: '500 mg' }, { label: 'L-Valina', value: '500 mg' }],
    officialUrl: 'https://beverly.es/collections/aminoacidos',
  },
  {
    id: 'map-300g',
    name: 'M.A.P. Essential Amino Acids 300g',
    price: 36.5,
    image: officialImage('MAP - Aminoácidos esenciales - 300 g - Blue Lollipop'),
    flavors: ['Blue Lollipop', 'Watermelon'],
    description: 'Fórmula con los nueve aminoácidos esenciales y vitamina B6.',
    longDescription: 'Aminoácidos esenciales en polvo para complementar la pauta nutricional y deportiva.',
    category: 'Recuperación & Aminoácidos',
    categories: ['Recuperación & Aminoácidos'],
    format: '300 g en polvo',
    serving: '15 g',
    use: 'Mezclar 15 g en 200 ml de agua.',
    technical: [{ label: 'L-Leucina', value: '3.400 mg' }, { label: 'L-Lisina', value: '2.200 mg' }, { label: 'L-Isoleucina', value: '1.800 mg' }, { label: 'L-Valina', value: '1.800 mg' }],
    officialUrl: 'https://beverly.es/products/map-300-g-blue-lollipop',
  },
  {
    id: 'dynamite-pre-workout',
    name: 'Dynamite Pre-Workout 375g',
    price: 32.9,
    image: officialImage('Dynamite Pre Workout - 375 g - 25 Servings - Fruit Punch'),
    flavors: ['Fruit Punch', 'Blue Lollipop'],
    description: 'Pre-entreno con creatina Creapure®, beta-alanina, citrulina y cafeína.',
    longDescription: 'Fórmula pre-entreno de 25 servicios. Contiene estimulantes y debe respetarse el etiquetado del fabricante.',
    category: 'Pre-entreno & Energía',
    categories: ['Pre-entreno & Energía', 'Creatina & Fuerza'],
    badge: '25 servicios',
    format: '375 g en polvo',
    serving: '15 g',
    use: 'Tomar la ración indicada aproximadamente 30 minutos antes del entrenamiento. Contiene cafeína.',
    technical: [{ label: 'Creatina Creapure®', value: '3.000 mg' }, { label: 'Beta-Alanina CarnoSyn®', value: '2.000 mg' }, { label: 'L-Citrulina Malato', value: '2.000 mg' }],
    officialUrl: 'https://beverly.es/products/dynamite-pre-workout-375-g-25-servings-fruit-punch',
    note: 'Producto con cafeína. Revisar advertencias completas del envase.',
  },
  {
    id: 'energy-pro-90',
    name: 'Energy Pro 90 caps',
    price: 19.9,
    image: officialImage('Energy Pro - Cafeína + Taurina - 90 Caps - 90 Servings'),
    flavors: ['Cápsulas'],
    description: 'Cafeína y taurina en cápsula.',
    longDescription: 'Complemento concentrado para adultos con cafeína y taurina.',
    category: 'Pre-entreno & Energía',
    categories: ['Pre-entreno & Energía'],
    format: '90 cápsulas',
    serving: '1 cápsula',
    use: 'Seguir la dosis indicada en el envase y evitar combinar con otras fuentes altas de cafeína.',
    technical: [{ label: 'L-Taurina', value: '400 mg' }, { label: 'Cafeína', value: '200 mg' }],
    officialUrl: 'https://beverly.es/products/energy-pro-caffeine-taurine-90-caps',
    note: 'Contiene cafeína.',
  },
  {
    id: 'vitamin-complex-90',
    name: 'Vitamin Complex 90 caps',
    price: 14.9,
    image: officialImage('Vitamin Complex multivitamínico y mineral - 90 Caps - 90 Servicios'),
    flavors: ['Cápsulas'],
    description: 'Complejo diario de vitaminas y minerales.',
    longDescription: 'Multivitamínico y mineral con vitaminas A, C, D3, E, K1, grupo B y minerales.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar'],
    format: '90 cápsulas · 90 servicios',
    serving: '1 cápsula',
    use: 'Tomar según la indicación de la etiqueta, preferentemente con una comida.',
    technical: [{ label: 'Vitamina C', value: '80 mg' }, { label: 'Calcio', value: '200 mg' }, { label: 'Magnesio', value: '75 mg' }, { label: 'Zinc', value: '10 mg' }],
    officialUrl: 'https://beverly.es/products/vitamin-complex-multivitaminico-y-mineral-90-caps',
  },

  // 20 nuevas referencias incorporadas en agosto de 2026.
  {
    id: 'isolate-cfm-1kg',
    name: 'Isolate CFM Professional 1kg',
    price: 51.9,
    image: officialImage('Isolate CFM Professional - 1 Kg - Butter Biscuit'),
    flavors: ['Butter Biscuit', 'Choco Cookies', 'Choco Hazelnut', 'Vainilla Ice Cream', 'Strawberry', 'Strawberry Cheesecake'],
    description: 'Aislado de suero Lacprodan® SP-9226 con DigeZyme® y Tolerase® L.',
    longDescription: 'Proteína aislada de alta concentración con seis sabores en la gama actual.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Aislado',
    format: '1 kg en polvo',
    serving: '35 g',
    use: 'Mezclar 35 g con agua, leche o bebida vegetal.',
    technical: [{ label: 'Proteína', value: '30,8 g por 35 g (Butter Biscuit)' }, { label: 'Hidratos', value: '0,6 g' }, { label: 'Grasas', value: '0,4 g' }, { label: 'DigeZyme®', value: '35 mg' }],
    officialUrl: 'https://beverly.es/products/isolate-cfm-professional-1-kg-butter-biscuit',
  },
  {
    id: 'isolate-cfm-2kg',
    name: 'Isolate CFM Professional 2kg',
    price: 94.9,
    image: officialImage('Isolate CFM Professional - 2 Kg - Butter Biscuit'),
    flavors: ['Butter Biscuit', 'Choco Cookies', 'Choco Hazelnut', 'Vainilla Ice Cream', 'Strawberry', 'Strawberry Cheesecake'],
    description: 'Formato 2 kg del aislado CFM Professional con Lacprodan®.',
    longDescription: 'Misma familia Isolate CFM Professional en formato grande, con seis sabores actuales.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Formato ahorro',
    format: '2 kg en polvo',
    serving: '35 g',
    use: 'Mezclar 35 g con agua, leche o bebida vegetal.',
    technical: [{ label: 'Proteína', value: '30,8 g por 35 g (Butter Biscuit)' }, { label: 'Hidratos', value: '0,6 g' }, { label: 'Grasas', value: '0,4 g' }],
    officialUrl: 'https://beverly.es/en/products/isolated-protein-cfm-2kg-butter-biscuit',
  },
  {
    id: 'hydro-protein-1kg',
    name: 'Hydro Protein 1kg',
    price: 46.9,
    image: officialImage('Hydro Protein - 1 Kg - Banana'),
    flavors: ['Banana', 'Lemon Cheesecake'],
    description: 'Proteína de suero hidrolizada en formato 1 kg.',
    longDescription: 'Opción hidrolizada de la gama Beverly para quienes prefieren una proteína de rápida digestión.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '1 kg en polvo',
    serving: '35 g',
    use: 'Mezclar una toma con agua, leche o bebida vegetal y seguir la etiqueta.',
    technical: [{ label: 'Tipo', value: 'Proteína de suero hidrolizada' }, { label: 'Formato', value: '1 kg' }],
    officialUrl: 'https://beverly.es/collections/proteinas',
  },
  {
    id: 'hydro-protein-2kg',
    name: 'Hydro Protein Professional 2kg',
    price: 84.9,
    image: officialImage('Hydro Protein Professional - 2 Kg - Chocolate'),
    flavors: ['Chocolate', 'Cookies and Cream', 'Strawberry'],
    description: 'Proteína de suero hidrolizada con DigeZyme® y Tolerase® L.',
    longDescription: 'Formato profesional de 2 kg de proteína hidrolizada.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '2 kg en polvo',
    serving: '35 g',
    use: 'Mezclar 35 g con agua, leche o bebida vegetal.',
    technical: [{ label: 'Proteína', value: '28,4 g por 35 g (Chocolate)' }, { label: 'Hidratos', value: '2,2 g' }, { label: 'Grasas', value: '1,4 g' }, { label: 'DigeZyme®', value: '35 mg' }],
    officialUrl: 'https://beverly.es/products/hydro-professional-protein-2-kg-chocolate',
  },
  {
    id: 'clear-isolate-500g',
    name: 'Clear Isolate Protein 500g',
    price: 31.9,
    image: officialImage('Clear Isolate Protein - 500 g - Orange Mango'),
    flavors: ['Orange Mango', 'Strawberry Kiwi', 'Lemon'],
    description: 'Aislado de suero de textura ligera y transparente.',
    longDescription: 'Clear protein con Lacprodan® ClearShake, pensada como alternativa tipo bebida refrescante.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'Clear',
    format: '500 g en polvo',
    serving: '30 g en tabla nutricional',
    use: 'Mezclar preferiblemente con agua fría. Revisar la ración del envase.',
    technical: [{ label: 'Proteína', value: '25,5 g por 30 g' }, { label: 'Hidratos', value: '0,6 g' }, { label: 'Grasas', value: '0,05 g' }],
    officialUrl: 'https://beverly.es/en/products/clear-isolate-protein-500-g-orange-mango',
  },
  {
    id: 'pure-whey-1kg',
    name: 'Pure Whey 1kg',
    price: 51,
    image: officialImage('Pure Whey - 1 Kg'),
    flavors: ['Sin sabor'],
    description: 'Whey concentrada sin aromas, edulcorantes ni colorantes.',
    longDescription: 'Proteína concentrada Lacprodan® para quien busca una fórmula sin sabor añadido.',
    category: 'Proteínas',
    categories: ['Proteínas'],
    format: '1 kg en polvo',
    serving: '35 g',
    use: 'Mezclar 35 g con agua, leche o bebida vegetal.',
    technical: [{ label: 'Proteína', value: '28 g por 35 g' }, { label: 'Hidratos', value: '2,2 g' }, { label: 'Grasas', value: '2,1 g' }],
    officialUrl: 'https://beverly.es/products/pure-whey-1-kg',
  },
  {
    id: 'whey-pro-concentrate-1kg',
    name: 'Whey Pro Concentrate 1kg',
    price: 41.65,
    image: officialImage('Whey Pro Concentrate - 1 Kg - Choco Cookies'),
    flavors: ['Choco Cookies', 'Strawberry', 'Strawberry Cheesecake', 'Vainilla Ice Cream'],
    description: 'La Whey Pro Concentrate en formato 1 kg.',
    longDescription: 'Concentrado de suero Lacprodan® SP-8011 con complejo enzimático.',
    category: 'Proteínas',
    categories: ['Proteínas', 'Recuperación & Aminoácidos'],
    format: '1 kg en polvo',
    serving: '35 g',
    use: 'Mezclar 35 g con agua, leche o bebida vegetal.',
    technical: [{ label: 'Proteína', value: '26,8 g por 35 g (Choco Cookies)' }, { label: 'Hidratos', value: '2,1 g' }, { label: 'DigeZyme®', value: '35 mg' }],
    officialUrl: 'https://beverly.es/products/whey-pro-concentrate-1-kg-choco-cookies',
  },
  {
    id: 'creapure-300g',
    name: 'Creatina Monohidrato Creapure® 300g',
    price: 32.95,
    image: officialImage('Creatina Monohidrato Creapure® - 300 g - Unflavored'),
    flavors: ['Unflavored', 'Cherry', 'Orange Mango'],
    description: 'Creatina monohidrato Creapure® en formato 300 g.',
    longDescription: 'Creatina monohidrato con sello Creapure®; la versión neutra declara 3 g por servicio.',
    category: 'Creatina & Fuerza',
    categories: ['Creatina & Fuerza'],
    badge: 'Creapure®',
    format: '300 g en polvo',
    serving: '3 g',
    use: 'Mezclar 3 g en 200 ml de agua.',
    ingredients: 'Creatina monohidrato Creapure® en la variante neutra.',
    technical: [{ label: 'Creatina Monohidrato Creapure®', value: '3 g por servicio' }],
    officialUrl: 'https://beverly.es/products/creatine-monohydrate-creapure-300-g-unflavored',
  },
  {
    id: 'creapure-q10-300g',
    name: 'Creatina Creapure® + Coenzima Q10 300g',
    price: 33.9,
    image: officialImage('Creatina Monohidrato Creapure® + Coenzima Q10 - 300 g - Sandía'),
    flavors: ['Sandía'],
    description: 'Creatina Creapure® combinada con coenzima Q10.',
    longDescription: 'Fórmula For Her de 3 g por servicio con creatina monohidrato y coenzima Q10.',
    category: 'Creatina & Fuerza',
    categories: ['Creatina & Fuerza', 'For Her'],
    format: '300 g en polvo',
    serving: '3 g',
    use: 'Mezclar 3 g en 200 ml de agua.',
    technical: [{ label: 'Creatina Monohidrato Creapure®', value: '2.900 mg' }, { label: 'Coenzima Q10', value: '100 mg' }],
    officialUrl: 'https://beverly.es/products/creatina-monohidrato-creapure%C2%AE-for-her-300-g-watermelon',
  },
  {
    id: 'l-citrulina-malato-300g',
    name: 'L-Citrulina Malato 300g',
    price: 21.5,
    image: officialImage('L-Citrulina Malato - 300 g - Unflavored'),
    flavors: ['Unflavored'],
    description: 'L-citrulina-DL-malato 2:1, sin mezclas.',
    longDescription: 'Fórmula 100% L-citrulina-DL-malato en proporción 2:1.',
    category: 'Pre-entreno & Energía',
    categories: ['Pre-entreno & Energía'],
    format: '300 g en polvo',
    serving: '5 g',
    use: 'Mezclar 5 g en 200 ml de agua según la indicación del fabricante.',
    ingredients: 'L-citrulina-DL-malato (100%).',
    technical: [{ label: 'L-Citrulina-DL-Malato (2:1)', value: '5 g' }, { label: 'de la cual L-Citrulina', value: '3,4 g' }],
    officialUrl: 'https://beverly.es/products/l-citrulina-malato-300-g-unflavored',
  },
  {
    id: 'l-glutamina-kyowa-300g',
    name: 'L-Glutamina Kyowa® 300g',
    price: 19,
    image: officialImage('L-Glutamina Kyowa® - 300 g - Unflavored'),
    flavors: ['Unflavored', 'Cherry', 'Blue Lollipop'],
    description: 'L-glutamina Kyowa® en polvo.',
    longDescription: 'Referencia de aminoácidos de Beverly disponible actualmente en varios sabores.',
    category: 'Recuperación & Aminoácidos',
    categories: ['Recuperación & Aminoácidos', 'Salud & Bienestar'],
    format: '300 g en polvo',
    serving: 'Consultar etiqueta de la variante',
    use: 'Seguir la dosificación de la etiqueta física de la variante elegida.',
    ingredients: 'L-glutamina Kyowa®; aromas y otros ingredientes pueden variar según sabor.',
    technical: [{ label: 'Ingrediente principal', value: 'L-Glutamina Kyowa®' }, { label: 'Formato', value: '300 g' }],
    officialUrl: 'https://beverly.es/collections/cuidado-personal',
  },
  {
    id: 'magnesium-bisglycinate-b6',
    name: 'Bisglicinato de Magnesio + B6 90 caps',
    price: 12.95,
    image: officialImage('Bisglicinato de Magnesio + Vitamin B6 - 90 Caps - 90 Servicios'),
    flavors: ['Cápsulas'],
    description: 'Bisglicinato de magnesio con vitamina B6.',
    longDescription: 'Complemento de magnesio y vitamina B6 en formato de 90 servicios.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar'],
    format: '90 cápsulas · 90 servicios',
    serving: '1 cápsula',
    use: 'Tomar 1 cápsula al día con agua según la ficha del fabricante.',
    technical: [{ label: 'Bisglicinato de Magnesio', value: '450 mg' }, { label: 'Vitamina B6', value: '1,4 mg' }],
    officialUrl: 'https://beverly.es/products/magnesium-bisglycinate-vitamin-b6-90-caps',
  },
  {
    id: 'vitamin-d3-k2',
    name: 'Vitamina D3 + K2 60 caps',
    price: 12.9,
    image: officialImage('Vitamina D3 + K2 - 60 Caps - 60 Servicios'),
    flavors: ['Cápsulas'],
    description: 'Combinación de vitamina D3 y vitamina K2.',
    longDescription: '60 cápsulas y 60 servicios de D3 + K2 según la formulación actual de Beverly.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar'],
    format: '60 cápsulas · 60 servicios',
    serving: '1 cápsula',
    use: 'Tomar 1 cápsula al día con una comida según la etiqueta.',
    technical: [{ label: 'Vitamina D3', value: '4.000 UI / 100 µg' }, { label: 'Vitamina K2 (MK-7)', value: '100 µg' }],
    officialUrl: 'https://beverly.es/products/vitamin-d3-k2-60-caps',
  },
  {
    id: 'ashwagandha-ksm66',
    name: 'Ashwagandha KSM-66 + Magnesio 60 caps',
    price: 29.5,
    image: officialImage('Ashwagandha KSM-66 + Magnesio, L-Teanina & Rhodiola - 60 Caps - 60 Servicios'),
    flavors: ['Cápsulas'],
    description: 'Ashwagandha KSM-66® con magnesio, L-teanina y rhodiola.',
    longDescription: 'Fórmula de bienestar y adaptación al estrés con cuatro componentes principales.',
    category: 'Salud & Bienestar',
    categories: ['Salud & Bienestar', 'Recuperación & Aminoácidos'],
    format: '60 cápsulas',
    serving: 'Consultar etiqueta',
    use: 'Seguir la pauta indicada en el envase.',
    technical: [{ label: 'Fórmula', value: 'KSM-66® + Magnesio + L-Teanina + Rhodiola' }, { label: 'Formato', value: '60 cápsulas' }],
    officialUrl: 'https://beverly.es/products/ashwagandha-ksm66-60-caps',
  },
  {
    id: 'b-complex-60',
    name: 'B-Complex 60 caps',
    price: 27.9,
    image: officialImage('B-Complex - 60 Caps - 60 Servicios'),
    flavors: ['Cápsulas'],
    description: 'Complejo de vitaminas del grupo B.',
    longDescription: 'Fórmula de 60 servicios con vitaminas B1, B2, B3, B5, B6, B9, B12, biotina, colina, inositol y PABA.',
    category: 'Vitaminas & Minerales',
    categories: ['Vitaminas & Minerales', 'Salud & Bienestar'],
    format: '60 cápsulas · 60 servicios',
    serving: '1 cápsula',
    use: 'Tomar 1 cápsula al día con una comida según la ficha del fabricante.',
    technical: [{ label: 'Vitamina B1', value: '100 mg' }, { label: 'Vitamina B6', value: '10 mg' }, { label: 'Ácido fólico', value: '400 µg' }, { label: 'Vitamina B12', value: '100 µg' }],
    officialUrl: 'https://beverly.es/products/b-complex-60-caps',
  },
  {
    id: 'women-protein-500g',
    name: 'Women Protein Shake 500g',
    price: 27.9,
    image: officialImage('Women Protein Shake - 500 g - Chocolate'),
    flavors: ['Chocolate', 'Petit Beurre', 'Strawberry White Chocolate', 'Capuccino'],
    description: 'Proteína con colágeno marino Peptan®, magnesio y vitamina E.',
    longDescription: 'Mezcla de proteína aislada y concentrada con colágeno Peptan®, magnesio, vitamina E y enzimas digestivas.',
    category: 'For Her',
    categories: ['For Her', 'Proteínas', 'Recuperación & Aminoácidos'],
    badge: 'For Her',
    format: '500 g en polvo',
    serving: '30 g en tabla nutricional',
    use: 'La ficha nutricional expresa valores por 30 g y el texto de uso menciona 35 g; prevalece el etiquetado físico.',
    technical: [{ label: 'Proteína', value: '26,8 g por 30 g (Chocolate)' }, { label: 'Colágeno Peptan®', value: '5 g' }, { label: 'Magnesio', value: '160 mg' }, { label: 'Vitamina E', value: '7,5 mg' }],
    officialUrl: 'https://beverly.es/products/women-protein-shake-500-g-chocolate',
  },
  {
    id: 'collagen-for-her-20',
    name: 'Collagen For Her 20 viales',
    price: 36.9,
    image: officialImage('Collagen For Her + Biotina, Vitamina C y Ácido hialurónico - Frutos del bosque - 20 Viales'),
    flavors: ['Frutos del bosque'],
    description: 'Colágeno Peptan® con vitamina C, biotina, zinc y ácido hialurónico.',
    longDescription: 'Formato de 20 viales líquidos de la línea For Her.',
    category: 'For Her',
    categories: ['For Her', 'Salud & Bienestar'],
    format: '20 viales',
    serving: '1 vial',
    use: 'Tomar 1 vial al día y agitar antes de consumir, según la etiqueta.',
    technical: [{ label: 'Colágeno Peptan®', value: '5.000 mg por vial' }, { label: 'Vitamina C', value: '102,5 mg' }, { label: 'Ácido hialurónico', value: '17,5 mg' }, { label: 'Zinc', value: '10,5 mg' }],
    officialUrl: 'https://beverly.es/products/collagen-for-her-biotine-vitamin-c-20-viales',
  },
  {
    id: 'burner-extreme-90',
    name: 'Burner Extreme 90 caps',
    price: 31.6,
    image: officialImage('Burner Extreme - Quemador de grasa - 90 Caps - 22 Servicios'),
    flavors: ['Cápsulas'],
    description: 'Fórmula termogénica con Sinetrol®, acetil L-carnitina, té verde y cafeína.',
    longDescription: 'Producto con estimulantes de la categoría de control de peso. No sustituye una dieta adecuada ni el ejercicio.',
    category: 'Control de peso',
    categories: ['Control de peso', 'Pre-entreno & Energía'],
    format: '90 cápsulas · 22 servicios',
    serving: '4 cápsulas',
    use: 'Seguir estrictamente la indicación del fabricante. Contiene cafeína y sinefrina.',
    technical: [{ label: 'Sinetrol® XPUR', value: '500 mg' }, { label: 'Acetil L-Carnitina', value: '500 mg' }, { label: 'Té verde', value: '200 mg' }, { label: 'Cafeína anhidra', value: '175 mg' }],
    officialUrl: 'https://beverly.es/products/burner-extreme-quemador-de-grasa-90-caps-22-servicios',
    note: 'Complemento con estimulantes. Revisar contraindicaciones y advertencias del envase.',
  },
  {
    id: 'carni-xtreme-20',
    name: 'Carni Xtreme Carnipure® 20 viales',
    price: 29.95,
    image: officialImage('Carni Xtreme - Carnitina líquida Carnipure® - 20 viales - Frutos rojos'),
    flavors: ['Frutos rojos'],
    description: 'L-carnitina líquida Carnipure® en viales.',
    longDescription: 'Formato líquido de 20 viales dentro de la gama de control de peso y rendimiento de Beverly.',
    category: 'Control de peso',
    categories: ['Control de peso', 'Pre-entreno & Energía'],
    format: '20 viales',
    serving: 'Consultar etiqueta',
    use: 'Seguir la pauta del envase de la formulación actual.',
    technical: [{ label: 'Ingrediente destacado', value: 'L-Carnitina Carnipure®' }, { label: 'Formato', value: '20 viales' }],
    officialUrl: 'https://beverly.es/collections/quemadores-y-diureticos',
  },
  {
    id: 'energy-go-gel-12',
    name: 'Energy Go Gel 12 sticks',
    price: 23.75,
    image: officialImage('Energy Go Gel energético - 12 Sticks Gel - 73,2 g - Apple'),
    flavors: ['Apple'],
    description: 'Gel energético en formato individual para actividad física.',
    longDescription: 'Caja de 12 sticks de gel de la gama pre-entreno y energía de Beverly.',
    category: 'Pre-entreno & Energía',
    categories: ['Pre-entreno & Energía'],
    format: '12 sticks gel',
    serving: '1 stick',
    use: 'Utilizar según el etiquetado y las necesidades de la actividad deportiva.',
    technical: [{ label: 'Formato', value: '12 sticks' }, { label: 'Sabor', value: 'Apple' }],
    officialUrl: 'https://beverly.es/collections/pre-entrenos',
  },
]

export const collagenPromo: Product = {
  id: 'promo-colageno-2-cajas',
  name: 'Pack Colágeno Marino · 2 cajas',
  price: 65,
  regularPrice: 73.8,
  image: 'https://beverly.es/cdn/shop/files/pruebaweb_d64f1683-bf88-47a7-bc17-828215d4d053.jpg?v=1766496350&width=1200',
  flavors: ['Frutos del bosque · 40 viales'],
  description: 'Dos cajas de colágeno Peptan® con vitamina C, biotina, zinc y ácido hialurónico.',
  longDescription: 'Pack de 40 viales líquidos de la formulación actual de Beverly.',
  category: 'For Her',
  categories: ['For Her', 'Salud & Bienestar'],
  badge: 'Pack ahorro',
  format: '2 × 20 viales',
  serving: '1 vial',
  use: 'Tomar 1 vial al día y agitar antes de consumir, según el etiquetado.',
  technical: [{ label: 'Colágeno Peptan®', value: '5.000 mg por vial' }, { label: 'Vitamina C', value: '102,5 mg' }, { label: 'Ácido hialurónico', value: '17,5 mg' }, { label: 'Zinc', value: '10,5 mg' }],
  officialUrl: 'https://beverly.es/products/collagen-for-her-biotine-vitamin-c-20-viales',
}

export const catalog = [collagenPromo, ...products]

export function getProduct(productId: string) {
  return catalog.find((product) => product.id === productId)
}

export function formatPrice(value: number) {
  return new Intl.NumberFormat('es-ES', {
    style: 'currency',
    currency: 'EUR',
  }).format(value)
}
